// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4TnwmTX5Y01q41yc2Gf9fYFDeOU2u6E',
    appId: '1:82423488286:web:5193239531141b6eeeb30f',
    messagingSenderId: '82423488286',
    projectId: 'plantconnect-7dd0c',
    authDomain: 'plantconnect-7dd0c.firebaseapp.com',
    storageBucket: 'plantconnect-7dd0c.firebasestorage.app',
    measurementId: 'G-PVC0CLCF8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHuAAX-lzYGu8HjhremjslJHNAN3CK4g',
    appId: '1:82423488286:android:7df6c2049472000deeb30f',
    messagingSenderId: '82423488286',
    projectId: 'plantconnect-7dd0c',
    storageBucket: 'plantconnect-7dd0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLF6F8JtTWtd0zhdwBEkOQWtNLUYe5Gg',
    appId: '1:82423488286:ios:207d1502034e3e62eeb30f',
    messagingSenderId: '82423488286',
    projectId: 'plantconnect-7dd0c',
    storageBucket: 'plantconnect-7dd0c.firebasestorage.app',
    iosBundleId: 'com.example.plantconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE4TnwmTX5Y01q41yc2Gf9fYFDeOU2u6E',
    appId: '1:82423488286:web:78ba8274e6af650aeeb30f',
    messagingSenderId: '82423488286',
    projectId: 'plantconnect-7dd0c',
    authDomain: 'plantconnect-7dd0c.firebaseapp.com',
    storageBucket: 'plantconnect-7dd0c.firebasestorage.app',
    measurementId: 'G-7RX8NX2DD5',
  );
}
